### ISSUE TITLE
Provide a set of benchmarks / validations that will check the user platform and guesstimate how much storage could be commited

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/post#102]
We need to create some "bench" so no one commits too much storage. We need to make sure that:
* benchmark the proof time generation (per space unit)
  * measure disk speed
  * measure CPU speed
  * measure GPU speed for data generation -> that's kinda nice to have part.
* benchmark the proof validation (per proof)

**Comment by pigmej** [comment]
This have to wait for https://github.com/spacemeshos/post/issues/105

**Comment by pigmej** [comment]
@poszu do we need sth more there? What about our current tool? Isn't it https://github.com/spacemeshos/post-rs/issues/34 ?

**Comment by poszu** [comment]
Yes, the benchmark tool is implemented in post-rs. Closing.
