### ISSUE TITLE
Add the POW to the AES invocations so running proving with multiple nonces is not that cheap.

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/post#104]
#### Description

We need to make using multiple (100s of thousands) nonces in proving harder. Therefore we need to add POW to the initial phase of AES.

#### Acceptance criteria

- Define POW algorithm together with the research team
   - The goal is to prevent an adversary to grind on challenges for keys that would allow them to generate a valid PoST proof with without having the labels stored on disk.
- Limit maximum nonce for a challenge to 40
   - This does not mean that the reference implementation of PoST uses 40 nonces to look for indices that satisfy the difficulty threshold. Just that when verifying a proof by another identity nonces >= 40 will be rendered invalid

**Comment by fasmat** [comment]
updated description @pigmej
