### ISSUE TITLE
We need to have a possibility to arbitrairly define start point for POST initialisation

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/post#123]
When let's say one is renting GPUs for initialisation or NOT using storage on the same device then it's very inconvenient to hope that the process never restarts.

We need a way to specify `--startFrom xyz` where `xyz` is file,labels

**Comment by fasmat** [comment]
I suggest to add the CLI flags `--from` and `--to` and make them the file indices defaulting to 0 and `(numUnits * labelsPerUnit * bytesPerLabel) / maxFileSize`

Programatically the initializer should just skip files outside of that range during initialization.

**Comment by fasmat** [comment]
This was added to `postcli` with https://github.com/spacemeshos/post/pull/179
