### ISSUE TITLE
Add POS verification to `postcli`

### ISSUE THREAD

**Issue by poszu** [spacemeshos/post#180]
Add a new command to postcli to verify POS data at a given location. The idea is to cross-check a randomly picked subset of labels in the POS data against labels generated with the CPU implementation.

**Comment by haverlinkfor** [comment]
All my nodes initialized with 0.8.7 version have invalid POS check
Nodes initialized with newer versions pass this check.
Doest it mean I have to reinitialize everything made on  0.8.7?

**Comment by pigmej** [comment]
@haverlinkfor likely there is some other error with your data, there were no logical changes in the data generation there.
