### ISSUE TITLE
Create a CLI wrapper for Initialize

### ISSUE THREAD

**Issue by beckmani** [spacemeshos/post#19]
We wish to be able to run "initialize" by post as CLI.
The CLI should be able to receive 3 arguments as follow:
1. --space - The total space for the init
2. --filesize - The size of each file in the init 
3. --homedir - The target path to save the init files

Example:
./post-init --space=104876 --filesize=262144

This will create init files of size 262144 bytes each in the default home dir

return value: Exit code =0 on success

**Comment by moshababo** [comment]
Closed by #20.
