### ISSUE TITLE
Add a -clean argument to postcli

### ISSUE THREAD

**Issue by chrisxch** [spacemeshos/post#218]
No spacemesh app should delete postbin data without explicit consent from the user.

I had a hairy few days after running either -verify or -genproof with all arguments expect numunits present. It took the default numunits of 4, ignored the postdata_metadata config and proceeded to wipe out TiBs of data it deemed redundant in the blink of an eye.

I've commented out the entire removeRedundantFiles routine in my local version but if there's a use case for it then it needs to be called explicitly ie by supplying -clean to postcli. It can't be chained into other calls as a side effect.

**Comment by lrettig** [comment]
This was addressed in #241
