### ISSUE TITLE
error: Failed to dial target host "0.0.0.0:50051": dial tcp 0.0.0.0:50051: connectex: No connection could be made because the target machine is actively reused it

### ISSUE THREAD

**Issue by WeirdoPunk** [spacemeshos/post#250]
When I run / grpcurl. exe - plaintext - d '' 0.0.0.0:50051 spacemesh. v1. ActivationService. Highest | jq - r '. atx. id. id' | base64- d | xxd - p - c 64
error:Failed to dial target host "0.0.0.0:50051": dial tcp 0.0.0.0:50051: connectex: No connection could be made because the target machine is actively reused itgg

**Comment by pigmej** [comment]
Most likely your node is not listening on that API port.
