### ISSUE TITLE
GPU-Post Integration

### ISSUE THREAD

**Issue by gavraz** [spacemeshos/post#37]
Copied from the Epic which was open in go-spacemesh about this task:

We want to implement a stand-alone desktop GPU post generator process that can be started from other local processes such as a full node and provide a simple post init and progress api to local clients.

- Must run on os x, linux and windows 10.
- Use the gpu-post c lib internally for post generation.
- Implement back-off when user interactivity is detected (@noamnelke idea)

**Comment by avive** [comment]
We already have an epic about this in this repo.

**Comment by noamnelke** [comment]
hmmm... from reading the title it looks like this was supposed to be the `go-spacemesh` part and should have stayed in that repo (#32 is for implementing GPU-PoST, while integrating it is related to the node).

However, the only thing in the description that might fit in the node repo is the last bullet.

I saw there are several issues related to this in the node repo, I'll try to organize all the issues in the next few weeks.
