### ISSUE TITLE
Verify post init-data feature

### ISSUE THREAD

**Issue by avive** [spacemeshos/post#51]
Add feature to verify an existing post data. User specifies the post params (including smesher id) and the method should run tests to verify that the post is valid for the smesher. The motivation of this is enabling users to verify if a post they created is valid without having to wait for the node to use it and to log errors in case it is invalid.

**Comment by fasmat** [comment]
https://github.com/spacemeshos/post/pull/184 has introduced verification of post data with `postcli`
